# Generated by Django 4.2.1 on 2023-05-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_friendship_first_id', to='User.user')),
                ('second_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_friendship_second_id', to='User.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('first_id', 'second_id'), name='user_friend_12_unique_con'),
        ),
        migrations.AddConstraint(
            model_name='userfriend',
            constraint=models.UniqueConstraint(fields=('second_id', 'first_id'), name='user_friend_21_unique_con'),
        ),
    ]
