# Generated by Django 4.2.1 on 2023-05-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_request_from_user_id', to='User.user')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_request_to_user_id', to='User.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('from_id',), name='friend_request_from_id_unique_con'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('to_id',), name='friend_request_to_id_unique_con'),
        ),
    ]
