# Generated by Django 4.2.1 on 2023-05-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_friendrequest_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='friend_request_from_id_unique_con',
        ),
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='friend_request_to_id_unique_con',
        ),
    ]
